### ISSUE TITLE
Receiving ">>> Request guard `…` is forwarding" messages with log_level=critical

### ISSUE THREAD

**Issue by jeeger** [rwf2/Rocket#2661] opened 2023-12-04 08:51 UTC
**Description**

I'm running a small Rocket application (written for learning). I've set the log level to `critical` for the release build. I've written a `FromRequest` implementation for a custom `UserId` type that returns a Forward result if it can't extract a user ID from the request cookies. Despite setting the log level to `critical` via `Rocket.toml`, Rocket still writes ">> Request guard `UserId` is forwarding." to the lock.

**To Reproduce**

Implement a custom type with a `FromRequest` implementation, and return an `Outcome::Forward`. Set the log level to `critical` in Rocket.toml. You will receive some "Forwarding" messages.

(I can try and write code to reproduce if necessary, but I hope the bug is clear enough without a repro)

**Expected Behavior**

No output about my custom type.

**Environment:**

 - OS Distribution and Kernel: various
 - Rocket Version: 0.5.0

**Comment by SergioBenitez** [comment] 2023-12-04 17:24
Can you post the complete log output, from the moment the application starts to the moment it logs the forward and the rest of the request?

**Comment by jeeger** [comment] 2023-12-05 10:23
Here you go!

```
Rocket has launched from http://127.0.0.1:8000
   >> Request guard `UserType` is forwarding.
Warning: Received SIGINT. Requesting shutdown.
```

**Comment by jeeger** [comment] 2023-12-05 10:24
rustc version is `rustc 1.76.0-nightly (a1a37735c 2023-11-23)`.

**Comment by SergioBenitez** [comment] 2023-12-06 02:11
I see a few options in Rocket:

   1) Get rid of `LogLevel`'s coalescing of logging levels and simply expose the 6 `log` levels. This would allow you to set the `LOG_LEVEL` to `error`, bypassing this message.
   2) Do nothing and wait for #21 to finally land.

A few options outside of Rocket:

   1) Register your own `log` logger before calling `build()`. Rocket won't replace it, and you can
      filter messages however you like. IE, with `env_logger`:

      ```rust
      #[launch]
      fn rocket() -> _ {
          env_logger::init();
        
          rocket::build()
      }
      ```

   2) Filter your logs post-facto.

I'm inclined to suggest we do 2) in Rocket, given the options available outside of Rocket. I wouldn't be opposed to a PR that implements 1), however, as long as the implementation keeps the existing log levels for backwards compatibility.

Given that there's no specific issue here, as things work as intended, I'm going to close this issue. But please feel free to submit a PR if you'd like to extend Rocket's log levels to make this easier to handle.

**Closed by SergioBenitez** 2023-12-06 02:11 UTC
Labels: triage

**Comment by jeeger** [comment] 2023-12-13 08:51
Thanks for the comprehensive answer!
